name: gcolor3 # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '2.4.0+git' # just for humans, typically '1.2+git' or '1.3.2'
license: GPL-2.0+
summary: A color selection dialog written in GTK+ 3 by Jente Hidskens
description: |
  Ever wanted to know the value of that color on your screen? Gcolor3 enables 
  you to pick the color from any pixel on your screen. It also offers a palette, 
  so that you can easily mix and match a couple of colors together.
  
  When you have found the perfect combination of colors, naturally you want to 
  save them. Gcolor3 allows you to conveniently save and retrieve colors.
  
  Gcolor3 is a color selection dialog written in GTK+ 3. It is much alike Gcolor2, 
  but uses the newer GTK+ version and other modernisations to better integrate 
  into your modern desktop.
  
  Attibutions: 
  Gcolor3 is written and maintained by Jens Hidskes. The summary and description
  were taken from the gcolor3 project website (https://www.hjdskes.nl/projects/gcolor3/).
  

grade: stable
confinement: strict

apps:
  gcolor3:
    command: usr/bin/gcolor3
    extensions: [gnome]
    plugs:
      - home
    slots:
      - dbus-daemon
    common-id: gcolor3

parts:
  gcolor3:
    plugin: meson
    source: https://gitlab.gnome.org/World/gcolor3.git
    meson-parameters: [--prefix=/snap/gcolor3/current/usr]
    build-packages:
      - libhandy-1-dev
      - libportal-dev
      - libportal-gtk3-dev
    organize:
      snap/gcolor3/current/usr: usr

slots:
  dbus-daemon:
    interface: dbus
    bus: session
    name: nl.hjdskes.gcolor3
