name: gcolor3
base: core22
version: '2.4.0+git'
license: GPL-2.0+
grade: stable
confinement: strict
compression: lzo

summary: A color selection dialog written in GTK+ 3 by Jente Hidskens
description: |
  Ever wanted to know the value of that color on your screen? Gcolor3
  enables you to pick the color from any pixel on your screen. It also
  offers a palette, so that you can easily mix and match a couple of
  colors together.

  When you have found the perfect combination of colors, naturally you
  want to save them. Gcolor3 allows you to conveniently save and
  retrieve colors.

  Gcolor3 is a color selection dialog written in GTK+ 3. It is much
  alike Gcolor2, but uses the newer GTK+ version and other modernisations
  to better integrate into your modern desktop.

  *Attribution*
  Gcolor3 is written and maintained by Jens Hidskes. The summary and
  description were taken from the gcolor3 project website
  (https://www.hjdskes.nl/projects/gcolor3/).


architectures:
  - build-on: [amd64]
    build-for: [amd64]
  - build-on: [arm64]
    build-for: [arm64]

apps:
  gcolor3:
    command: usr/bin/gcolor3
    extensions: [gnome]
    plugs:
      - home
    slots:
      - dbus-gcolor3
    desktop: usr/share/applications/nl.hjdskes.gcolor3.desktop
    common-id: gcolor3

parts:
  gcolor3:
    plugin: meson
    source: https://gitlab.gnome.org/World/gcolor3.git
    meson-parameters: [--prefix=/snap/gcolor3/current/usr]
    build-packages:
      - libhandy-1-dev
      - libportal-dev
      - libportal-gtk3-dev
    override-pull: |
      snapcraftctl pull

      # Point icon in the .desktop file to the correct location
      sed -i.bak -e 's|Icon=nl.hjdskes.gcolor3|Icon=/usr/share/icons/hicolor/scalable/apps/nl.hjdskes.gcolor3.svg|g' data/nl.hjdskes.gcolor3.desktop.in
      # Change application name in the .desktop file from 'Color Picker' to 'Gcolor3'
      sed -i.bak -e 's|Name=Color Picker|Name=Gcolor3|g' data/nl.hjdskes.gcolor3.desktop.in
    organize:
      snap/gcolor3/current/usr: usr

slots:
  dbus-gcolor3:
    interface: dbus
    bus: session
    name: nl.hjdskes.gcolor3
